`n`t`d .q.set'+`${((r<2)_x;"fcb"r:"%&"?*x;", "\:y)}.'" -> "\:'0:`:i/20.txt;
d:n!d;cs:c!{r!r<r:&|/'d=x}'c:&`c=t:n!t;fs:c_n!n<n
pulse:{z,/:\:$[`b=m:t z; y; y<`f=m; fs[z]=:0; `c=m; [cs[z;x]:y; ~&/cs z]; ()],/:\:d z}
r:`n`f`p`t!/:,/{x,',/{,/pulse .'x}\,(`button;0b;`broadcaster)}'1+!10000
*/exec #i by p from r where n<1001
lcm:{x*y div*|(*:){|x-0,*x*div/|x}/x,y}
lcm/exec *n by f from r where p,f in !cs `tg / input specific
